/**
 * \file
 * Functions and types for CRC-8-bit checks.
 *
 * Algorithm (bit-by-bit-fast) generated by pycrc v0.9.1, https://pycrc.org
 *
 */
#include "crc8.h"
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>



uint8_t getCRC8(const uint8_t *data, size_t data_len) {
    uint8_t crc = 0x00;
    uint8_t i;
    bool bit;
    uint8_t c;

    while (data_len--) {
        c = *data++;
        for (i = 0x80; i > 0; i >>= 1) {
            bit = crc & 0x80;
            if (c & i) {
                bit = !bit;
            }
            crc <<= 1;
            if (bit) {
                crc ^= 0x07;
            }
        }
        crc &= 0xff;
    }
    return crc & 0xff;
}

bool checkCRC8(const uint8_t crcToCheck, const uint8_t *data, size_t data_len) {
    uint8_t newCRC = getCRC8(data,data_len);

    if (crcToCheck == newCRC) {
        return true;
    } else {
        return false;
    }
}

